---

- name: installing nginx on centos..........
  yum:
    name: nginx
    state: latest
  when: ansible_os_family == 'RedHat'
  
- name: restarting nginx services ............
  systemd:
    name: nginx
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat'