---
- name: installing apache on ubuntu................
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: start and enable apache services ............
  systemd:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == 'Debian'